config/routes.rb
DumplingMatchmaker::Application.routes.draw do
  devise_for :users
  resources :requests
  root :to => "home#index"

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user,
    inverse_of: :requests

  validates_presence_of :soup
  validates_presence_of :user

  def self.today
    Request.where("created_at > ?", 1.days.ago)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :requests,
    inverse_of: :user,
    dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name
  validates_presence_of :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
    @requests = Request.today
  end

  def create
    @request = Request.new
    @request.soup = params["soup"]
    @request.user_id = current_user.id

    if @request.save
      redirect_to requests_path,
        notice: "Request Submitted"
    else
      render :new
    end
  end

  def new
    @request = Request.new
  end

  def destroy
    @request = Request.find(params[:id])
    @user = current_user
    SoupFulfillment.match(@user, @request.user, @request).deliver

    Request.find(params[:id]).destroy
    redirect_to requests_path,
    notice: 'Request Fulfilled!'

  end


  private

  def request_params
    params.require(:request).permit(:soup, :current_user)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="aligncenter twelve columns" >
  <div class="soup"><%= link_to 'Sign Up', new_user_registration_path, class: "large button" unless user_signed_in? %></div>

  <% if user_signed_in? %>

    <div class="soup"><%= link_to 'Request Soup', new_request_path, class: "large button" %></div>
    <div class="soup"><%= link_to 'Fulfill a Soup Request', requests_path, class: "large button" %></div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Dumpling King Matchmaker</a></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <% if user_signed_in? %>
          <li><%= link_to 'Request a Soup', new_request_path %></li>
          <li class="divider"></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li>

          <div class="navbar-form">
            <%= simple_form_for("user", :url => user_session_path) do |f| %>
              <%= f.input :email, placeholder: 'Email', label: false %>
              <%= f.input :password, placeholder: 'Password', label: false %>
              <%= f.submit 'Sign In', class: "button sign-in-button" %>
            <% end %>
          </div>

          </li>
        <% end %>
      </ul>
      <ul class="left">
      </ul>
    </section>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Dumpling King Matchmaker</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div data-alert class="alert-box">
          <%= content_tag :div, msg %>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/requests/index.html.erb
<div class="small-12 large-8 small-centered large-centered column">
<h1 class="dumpling-table">Dumpling King Matcher</h1>
<h4 class="dumpling-table">Hurry quickly! These requests last only 24 hours.</h4>

<table class="dumpling-table twelve columns">
    <thead>
      <th>Name</th>
      <th>Soup</th>
      <th>Requested At</th>
      <th>Feeling Generous?</th>
    </thead>
    <tbody>
      <% @requests.each do |request| %>
      <tr>
        <td><%= request.user.first_name %> <%= request.user.last_name %></td>
        <td><%= request.soup %></td>
        <td><%= (request.created_at - 4.hours).strftime('%a. %B %d %r') %></td>
        <td><%= link_to 'Fulfill Request', request, method: :delete, data: { confirm: 'Click OK to Fulfill Request!' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/requests/new.html.erb
<div class="small-12 large-8 small-centered large-centered column aligncenter">
<h1>Make Your Soup Selection</h1>
  <div class="soup"><%= button_to 'Hot and Sour Soup', requests_path(soup: 'Hot and Sour Soup'), class: "large button" %></div>
  <div class="soup"><%= button_to 'Dumpling Soup', requests_path(soup: 'Dumpling Soup'), class: "large button" %></div>
</div>

app/views/requests/show.html.erb
<h1>Request Successfully Submitted</h1>

app/views/soup_fulfillment/match.text.erb
Hey <%= @requester.first_name %>. It's your lucky day!

<%= @fulfiller.first_name %> is going to purchase:

<%= @request.soup %> for you. Please be ready to pay $1

Enjoy!
The Dumpling King Matchmaker

:)